import 'package:flutter/material.dart';
import 'colors.dart';

class AppTheme {
  ThemeData get lightTheme {
    return ThemeData(
      useMaterial3: true,
      brightness: Brightness.light,
      visualDensity: VisualDensity.compact,
      colorScheme: const ColorScheme(
        brightness: Brightness.light,
        error: AppColors.errorColor,
        errorContainer: Color(0xFFFFDAD6),
        inversePrimary: Color(0xFFADD28E),
        inverseSurface: Color(0xFF2E312A),
        onError: AppColors.onErrorColor,
        onErrorContainer: Color(0xFF410002),
        onInverseSurface: Color(0xFFF0F2E7),
        onPrimary: AppColors.onPrimaryColor,
        onPrimaryContainer: Color(0xFF0B2000),
        onSecondary: AppColors.onSecondaryColor,
        onSecondaryContainer: Color(0xFF310048),
        onSurface: AppColors.onSurfaceColor,
        onSurfaceVariant: Color(0xFF44483E),
        onTertiary: Color(0xFFFFFFFF),
        onTertiaryContainer: Color(0xFF002020),
        outline: Color(0xFF74796D),
        outlineVariant: Color(0xFFC4C8BB),
        primary: AppColors.primaryColor,
        primaryContainer: AppColors.primaryContainer,
        scrim: Color(0xFF000000),
        secondary: AppColors.secondaryColor,
        secondaryContainer: AppColors.secondaryContainer,
        shadow: Color(0xFF000000),
        surface: AppColors.surfaceColor,
        surfaceContainerHighest: Color(0xFFE2E3D9),
        surfaceTint: Color(0xFF47672F),
        tertiary: Color(0xFF386665),
        tertiaryContainer: Color(0xFFBBECEA),
      ),
      appBarTheme: const AppBarTheme(
        titleTextStyle: TextStyle(
          color: AppColors.onPrimaryColor,
          fontFamily: 'Roboto',
          fontSize: 24,
          fontWeight: FontWeight.w400,
          letterSpacing: 0,
        ),
        toolbarTextStyle: TextStyle(
          color: AppColors.onPrimaryColor,
          fontFamily: 'Roboto',
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 1.25,
        ),
      ),
      bottomNavigationBarTheme: const BottomNavigationBarThemeData(
        selectedLabelStyle: TextStyle(
          color: AppColors.onPrimaryColor,
          fontFamily: 'Roboto',
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 1.25,
        ),
        unselectedLabelStyle: TextStyle(
          color: AppColors.onPrimaryColor,
          fontFamily: 'Roboto',
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 1.25,
        ),
      ),
      buttonTheme: ButtonThemeData(
        alignedDropdown: false,
        height: 36,
        layoutBehavior: ButtonBarLayoutBehavior.padded,
        minWidth: 88,
        padding: const EdgeInsets.symmetric(horizontal: 16),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
        ),
        textTheme: ButtonTextTheme.normal,
      ),
      canvasColor: AppColors.surfaceColor,
      cardColor: AppColors.surfaceColor,
      dialogBackgroundColor: AppColors.surfaceColor,
      disabledColor: const Color(0x61000000),
      dividerColor: const Color(0x1F191D16),
      focusColor: const Color(0x1F000000),
      highlightColor: const Color(0x66BCBCBC),
      hintColor: const Color(0x99000000),
      hoverColor: const Color(0x0A000000),
      iconTheme: const IconThemeData(
        color: Color(0xDD000000),
      ),
      indicatorColor: const Color(0xFFFFFFFF),
      primaryColor: AppColors.primaryColor,
      primaryColorDark: const Color(0xFF1976D2),
      primaryColorLight: const Color(0xFFBBDEFB),
      primaryIconTheme: const IconThemeData(
        color: AppColors.onPrimaryColor,
      ),
      scaffoldBackgroundColor: AppColors.surfaceColor,
      secondaryHeaderColor: const Color(0xFFE3F2FD),
      shadowColor: const Color(0xFF000000),
      splashColor: const Color(0x66C8C8C8),
      splashFactory: InkRipple.splashFactory,
      textTheme: const TextTheme(
        bodyLarge: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 16,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.5,
        ),
        bodyMedium: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 14,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.25,
        ),
        bodySmall: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 12,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.4,
        ),
        displayLarge: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora_300',
          fontSize: 96,
          fontWeight: FontWeight.w300,
          letterSpacing: -1.5,
        ),
        displayMedium: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora_300',
          fontSize: 60,
          fontWeight: FontWeight.w300,
          letterSpacing: -0.5,
        ),
        displaySmall: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 48,
          fontWeight: FontWeight.w400,
          letterSpacing: 0,
        ),
        headlineLarge: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 32,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.25,
        ),
        headlineMedium: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 34,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.25,
        ),
        headlineSmall: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 24,
          fontWeight: FontWeight.w400,
          letterSpacing: 0,
        ),
        labelLarge: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 1.25,
        ),
        labelMedium: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 11,
          fontWeight: FontWeight.w400,
          letterSpacing: 1.5,
        ),
        labelSmall: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 10,
          fontWeight: FontWeight.w400,
          letterSpacing: 1.5,
        ),
        titleLarge: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 20,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.15,
        ),
        titleMedium: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 16,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.15,
        ),
        titleSmall: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.1,
        ),
      ),
      primaryTextTheme: const TextTheme(
        bodyLarge: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 16,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.5,
        ),
        bodyMedium: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 14,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.25,
        ),
        bodySmall: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 12,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.4,
        ),
        displayLarge: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora_300',
          fontSize: 96,
          fontWeight: FontWeight.w300,
          letterSpacing: -1.5,
        ),
        displayMedium: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora_300',
          fontSize: 60,
          fontWeight: FontWeight.w300,
          letterSpacing: -0.5,
        ),
        displaySmall: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 48,
          fontWeight: FontWeight.w400,
          letterSpacing: 0,
        ),
        headlineLarge: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 32,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.25,
        ),
        headlineMedium: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 34,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.25,
        ),
        headlineSmall: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 24,
          fontWeight: FontWeight.w400,
          letterSpacing: 0,
        ),
        labelLarge: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 1.25,
        ),
        labelMedium: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 11,
          fontWeight: FontWeight.w400,
          letterSpacing: 1.5,
        ),
        labelSmall: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 10,
          fontWeight: FontWeight.w400,
          letterSpacing: 1.5,
        ),
        titleLarge: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 20,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.15,
        ),
        titleMedium: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 16,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.15,
        ),
        titleSmall: TextStyle(
          color: AppColors.onSurfaceColor,
          fontFamily: 'Sora',
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.1,
        ),
      ),
      tabBarTheme: const TabBarTheme(
        labelStyle: TextStyle(
          color: AppColors.onPrimaryColor,
          fontFamily: 'Roboto',
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.1,
        ),
        unselectedLabelStyle: TextStyle(
          color: AppColors.onPrimaryColor,
          fontFamily: 'Roboto',
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.1,
        ),
      ),
      typography: Typography.material2021(platform: TargetPlatform.iOS),
      applyElevationOverlayColor: false,
      platform: TargetPlatform.macOS,
      unselectedWidgetColor: const Color(0x8A000000),
      inputDecorationTheme: const InputDecorationTheme(
        alignLabelWithHint: false,
        filled: false,
        floatingLabelAlignment: FloatingLabelAlignment.start,
        floatingLabelBehavior: FloatingLabelBehavior.auto,
        isCollapsed: false,
        isDense: false,
      ),
      materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
    );
  }
}
